export const testData = [
    {id: 1, name: 'Ann', status: 'work'},
    {id: 2, name: 'Dan', status: 'work'},
    {id: 3, name: 'Poll', status: 'chill'},
    {id: 4, name: 'Jack', status: 'work'},
    {id: 5, name: 'Rick', status: 'no work'},
    {id: 6, name: 'Elli', status: 'no work'},
    {id: 7, name: 'Martina', status: 'no work'},
    {id: 8, name: 'Mark', status: 'search work'},
    {id: 9, name: 'Jay', status: 'searched'},
    {id: 10, name: 'May', status: 'searched'},
    {id: 11, name: 'Sally', status: 'searched'},
    {id: 12, name: 'Scott', status: 'working'},
    {id: 13, name: 'Styles', status: 'searched'},
    {id: 14, name: 'Liza', status: 'chill'},
    {id: 15, name: 'Mona', status: 'work'},
]
